-- GENERATED by tools/gen_tiles.py from the wow_test 1.60.1.12345 WDT files. Do not edit.
-- tiles[col * 64 + row] = minimap FileDataID for map<col>_<row>
-- bg = median colour of the water along the map's outer edge (for the backdrop)
-- kind = "dungeon" | "raid" for instances (nil: open world); continent = instanceID of the entrance's continent
if not MagicMap_WantTileSet("wow_test", "1.60.1.12345") then return end
MagicMap_ActiveProduct = "wow_test"
MagicMap_TileSets = MagicMap_TileSets or {}
MagicMap_TileSets["wow_test"] = { version = "1.60.1.12345", maps = {
  [0] = { name = "Eastern Kingdoms", bg = { 0.097, 0.143, 0.419 }, tiles = {
    [1950]=2000001, [1951]=2000003, [1952]=2000005, [1953]=2000007, [1954]=2000009, [2014]=2000011, [2015]=2000013, [2016]=2000015,
    [2017]=2000017, [2018]=2000019, [2078]=2000021, [2079]=2000023, [2080]=2000025, [2081]=2000027, [2082]=2000029, [2142]=2000031,
    [2143]=2000033, [2144]=2000035, [2145]=2000037, [2146]=2000039, [2206]=2000041, [2207]=2000043, [2208]=2000045, [2209]=2000047,
    [2210]=2000049,
  } },
  [1] = { name = "Kalimdor", bg = { 0.097, 0.143, 0.419 }, tiles = {
    [650]=3000001, [651]=3000003, [714]=3000005, [715]=3000007, [778]=3000009, [779]=3000011,
  } },
  [36] = { name = "Deadmines", bg = { 0.387, 0.381, 0.387 }, kind = "dungeon", continent = 0, tiles = {
    [1300]=4000001, [1364]=4000003,
  } },
} }
