#!/usr/bin/env perl
# Generate Data/Borders_<product>.lua: exact zone and subzone borders, plus
# label anchors, from the game's own terrain.
#
# Every ADT tile is split into 16x16 chunks (~33 yards) and each chunk (MCNK)
# records its AreaTable ID - the game's own definition of where zones and
# subzones are. AreaTable's parent links give each area's zone. We trace the
# chunk edges where the zone (or, within a zone, the subzone) changes, skip
# edges out in deep sea on both sides (so borders stop at the coast), chain
# the edges into polylines and simplify them. Label anchors are the land
# chunk deepest inside each area (farthest from its edge).
#
#   perl tools/gen_borders.pl "/Applications/World of Warcraft" wow_classic_beta > Data/Borders_wow_classic_beta.lua
use strict;
use warnings;
use FindBin;
use File::Temp qw(tempdir);
require "$FindBin::Bin/lib.pl";
our ($MAP_DB2, $AREATABLE_DB2);

my ($install, $product, $minTiles) = @ARGV;
die "usage: $0 INSTALL PRODUCT [minTiles]\n" unless $product;
$minTiles //= 20;
my $SEA_LEVEL = -2;      # chunks whose highest point is below this are open sea (zone borders stop)
my $SHORE_LEVEL = 0.5;   # ...below this, water: no subzone borders out there
my $MIN_SUBZONE_EDGE_CELLS = 4; # subzones smaller than this (land chunks) get no outline
my $SIMPLIFY = 0.4;      # Douglas-Peucker tolerance, in chunks
my $MIN_SUBZONE_CELLS = 6;

my $version = product_version($install, $product);
my $tmp = tempdir(CLEANUP => 1);
casc_extract($install, $product, $tmp, $MAP_DB2, $AREATABLE_DB2);

# AreaTable: id -> parent. Zone = root ancestor; subzone = the zone's child on the path.
my %parent;
for my $r (db2_rows("$tmp/$AREATABLE_DB2.bin", "0,1")) { $parent{$r->[0]} = $r->[4] }
sub zone_of { my ($a) = @_; for (1 .. 10) { last unless $parent{$a}; $a = $parent{$a} } return $a }
sub sub_of {
    my ($a) = @_;
    for (1 .. 10) { last unless $parent{$a} && $parent{$parent{$a}}; $a = $parent{$a} }
    return $a;
}

my @maps = world_maps("$tmp/$MAP_DB2.bin");
casc_extract($install, $product, $tmp, map { $_->[1] } @maps);

print "-- GENERATED by tools/gen_borders.pl from the $product $version terrain (ADT chunk areas). Do not edit.\n";
print "-- lines: { kind (1 zone, 2 subzone), areaA, areaB, fadeStart, fadeEnd, x1, y1, x2, y2, ... } in tile units\n";
print "-- labels: { areaID, col, row, weight (land chunks), kind }\n";
print "if MagicMap_ActiveProduct ~= \"$product\" then return end\n";
print "MagicMap_Borders = {\n";

for my $m (sort { $a->[0] <=> $b->[0] } @maps) {
    my ($inst, $wdt, $name) = @$m;
    next unless -e "$tmp/$wdt.bin";
    my $maid = wdt_maid(slurp("$tmp/$wdt.bin"));
    my @tileKeys = grep { $maid->{$_}[0] } keys %$maid;
    next if @tileKeys < $minTiles;

    # --- read chunk areas and heights ------------------------------------
    casc_extract($install, $product, $tmp, map { $maid->{$_}[0] } @tileKeys);
    my (%area, %sea, %wet);
    for my $key (@tileKeys) {
        my $file = "$tmp/$maid->{$key}[0].bin";
        next unless -e $file;
        my $b = slurp($file);
        unlink $file;
        my ($col, $row) = (int($key / 64), $key % 64);
        for (my $p = 0; $p + 8 <= length $b;) {
            my ($magic, $size) = unpack "a4 V", substr($b, $p, 8);
            if (reverse($magic) eq "MCNK" && $size >= 0x80) {
                my $d = substr($b, $p + 8, $size);
                my ($ix, $iy) = unpack "x4 V V", $d;
                my $areaId = unpack "V", substr($d, 0x34, 4);
                my $z = unpack "f<", substr($d, 0x70, 4);
                my $maxH = $z;
                my $mcvt = index($d, "TVCM", 0x80);
                if ($mcvt >= 0) {
                    for my $h (unpack "f<145", substr($d, $mcvt + 8, 580)) { $maxH = $z + $h if $z + $h > $maxH }
                }
                my $c = ($col * 16 + $ix) * 1024 + ($row * 16 + $iy);
                $area{$c} = $areaId;
                $sea{$c} = 1 if $maxH < $SEA_LEVEL;
                $wet{$c} = 1 if $maxH < $SHORE_LEVEL;
            }
            $p += 8 + $size;
        }
    }
    next unless %area;

    my (%zone, %sub);
    for my $c (keys %area) {
        next unless $area{$c};
        $zone{$c} = zone_of($area{$c});
        $sub{$c} = sub_of($area{$c});
    }
    my (%subLand, %zoneLand, %zoneAll);
    for my $c (keys %sub) {
        $zoneAll{$zone{$c}}++;
        next if $wet{$c};
        $subLand{$sub{$c}}++;
        $zoneLand{$zone{$c}}++;
    }
    # "Zones" that are mostly water (e.g. The Great Sea, even with a few islets)
    # aren't zones on a map.
    my %seaZone = map { $_ => 1 } grep { ($zoneLand{$_} // 0) < 10 || $zoneLand{$_} < $zoneAll{$_} * 0.25 } keys %zoneAll;
    for my $c (keys %zone) { delete $zone{$c} if $seaZone{$zone{$c}} }

    # --- edges between chunks --------------------------------------------
    # Vertices are chunk corners, key = vx * 1100 + vy.
    my @edges; # [kind, v1, v2, pair "a:b", a, b]
    for my $c (keys %area) {
        my ($gc, $gr) = (int($c / 1024), $c % 1024);
        for my $dir ([1, 0], [0, 1]) {
            my $n = ($gc + $dir->[0]) * 1024 + ($gr + $dir->[1]);
            next unless exists $area{$n};
            next if $sea{$c} && $sea{$n};
            my ($za, $zb) = ($zone{$c} // 0, $zone{$n} // 0);
            my ($kind, $a, $b);
            if ($za && $zb && $za != $zb) { ($kind, $a, $b) = (1, $za, $zb) }
            elsif ($za && $za == $zb && ($sub{$c} // 0) != ($sub{$n} // 0)) {
                # Subzones: only on land, and only for areas big enough to matter.
                next if $wet{$c} || $wet{$n};
                next if ($subLand{$sub{$c}} // 0) < $MIN_SUBZONE_EDGE_CELLS || ($subLand{$sub{$n}} // 0) < $MIN_SUBZONE_EDGE_CELLS;
                ($kind, $a, $b) = (2, $sub{$c}, $sub{$n});
            }
            else { next }
            ($a, $b) = ($b, $a) if $a > $b;
            my ($v1, $v2) = $dir->[0]
                ? (($gc + 1) * 1100 + $gr, ($gc + 1) * 1100 + $gr + 1)   # vertical edge
                : ($gc * 1100 + $gr + 1, ($gc + 1) * 1100 + $gr + 1);    # horizontal edge
            push @edges, [$kind, $v1, $v2, "$a:$b", $a, $b];
        }
    }

    my (%adj, %degree);
    for my $i (0 .. $#edges) {
        my $e = $edges[$i];
        push @{ $adj{$e->[1]} }, $i;
        push @{ $adj{$e->[2]} }, $i;
        $degree{$e->[1]}++;
        $degree{$e->[2]}++;
    }

    # --- chain edges of one kind + one area pair into polylines ------------
    my (%used, @lines);
    my $walk = sub {
        my ($start, $ei) = @_;
        my ($kind, $pair, $pa, $pb) = @{ $edges[$ei] }[0, 3, 4, 5];
        my @pts = ($start);
        my $node = $start;
        while (defined $ei && !$used{$ei}) {
            $used{$ei} = 1;
            my $e = $edges[$ei];
            $node = $e->[1] == $node ? $e->[2] : $e->[1];
            push @pts, $node;
            my @next = grep { !$used{$_} && $edges[$_][0] == $kind && $edges[$_][3] eq $pair } @{ $adj{$node} };
            my @same = grep { $edges[$_][0] == $kind && $edges[$_][3] eq $pair } @{ $adj{$node} };
            last unless @same == 2 && @next == 1;
            $ei = $next[0];
        }
        # A true dead end (nothing else meets it) fades out instead of stopping.
        my $fadeStart = $degree{$start} == 1 ? 1 : 0;
        my $fadeEnd = $degree{$node} == 1 ? 1 : 0;
        my @xy = map { [int($_ / 1100), $_ % 1100] } @pts;
        @xy = simplify(\@xy, $SIMPLIFY);
        push @lines, [$kind, $pa, $pb, $fadeStart, $fadeEnd, \@xy];
    };
    for my $v (keys %adj) {
        for my $ei (@{ $adj{$v} }) {
            next if $used{$ei};
            my $kind = $edges[$ei][0];
            my $pair = $edges[$ei][3];
            my @same = grep { $edges[$_][0] == $kind && $edges[$_][3] eq $pair } @{ $adj{$v} };
            $walk->($v, $ei) if @same != 2;
        }
    }
    for my $ei (0 .. $#edges) { # closed loops
        $walk->($edges[$ei][1], $ei) unless $used{$ei};
    }

    # --- label anchors: deepest land chunk of each zone / subzone ----------
    my @labels;
    for my $level ([1, \%zone], [2, \%sub]) {
        my ($kind, $ids) = @$level;
        my (%dist, @queue, %count);
        for my $c (keys %$ids) {
            next if $sea{$c};
            $count{$ids->{$c}}++;
            my ($gc, $gr) = (int($c / 1024), $c % 1024);
            for my $n (($gc - 1) * 1024 + $gr, ($gc + 1) * 1024 + $gr, $c - 1, $c + 1) {
                if (!exists $ids->{$n} || $sea{$n} || $ids->{$n} != $ids->{$c}) { $dist{$c} = 0; push @queue, $c; last }
            }
        }
        for (my $h = 0; $h < @queue; $h++) {
            my $c = $queue[$h];
            my ($gc, $gr) = (int($c / 1024), $c % 1024);
            for my $n (($gc - 1) * 1024 + $gr, ($gc + 1) * 1024 + $gr, $c - 1, $c + 1) {
                next if exists $dist{$n} || !exists $ids->{$n} || $sea{$n} || $ids->{$n} != $ids->{$c};
                $dist{$n} = $dist{$c} + 1;
                push @queue, $n;
            }
        }
        my %best;
        for my $c (keys %dist) {
            my $id = $ids->{$c};
            $best{$id} = $c if !defined $best{$id} || $dist{$c} > $dist{$best{$id}};
        }
        for my $id (sort { $a <=> $b } keys %best) {
            next if $kind == 2 && ($count{$id} < $MIN_SUBZONE_CELLS || $id == zone_of($id));
            my $c = $best{$id};
            push @labels, [$id, (int($c / 1024) + 0.5) / 16, ($c % 1024 + 0.5) / 16, $count{$id}, $kind];
        }
    }

    printf STDERR "%s: [%d] %s: %d zone lines, %d subzone lines, %d labels\n", $product, $inst, $name,
        scalar(grep { $_->[0] == 1 } @lines), scalar(grep { $_->[0] == 2 } @lines), scalar @labels;

    print "  [$inst] = { -- ", $name =~ s/\n/ /gr, "\n    lines = {\n";
    for my $l (sort { $a->[0] <=> $b->[0] } @lines) {
        my ($kind, $a, $b, $fs, $fe, $xy) = @$l;
        print "      { $kind, $a, $b, $fs, $fe, ",
            join(", ", map { sprintf("%.2f, %.2f", $_->[0] / 16, $_->[1] / 16) } @$xy), " },\n";
    }
    print "    },\n    labels = {\n";
    for my $l (@labels) { printf "      { %d, %.2f, %.2f, %d, %d },\n", @$l }
    print "    },\n  },\n";
}
print "}\n";

# Douglas-Peucker on [[x, y], ...].
sub simplify {
    my ($pts, $tol) = @_;
    my $n = @$pts;
    return @$pts if $n <= 2;
    my %keep = (0 => 1, $n - 1 => 1);
    my @stack = ([0, $n - 1]);
    while (my $s = pop @stack) {
        my ($i, $j) = @$s;
        my ($ax, $ay, $bx, $by) = (@{ $pts->[$i] }, @{ $pts->[$j] });
        my ($dx, $dy) = ($bx - $ax, $by - $ay);
        my $len = sqrt($dx * $dx + $dy * $dy);
        my ($worst, $worstD) = (undef, $tol);
        for my $k ($i + 1 .. $j - 1) {
            my ($px, $py) = @{ $pts->[$k] };
            my $d = $len < 1e-9 ? sqrt(($px - $ax) ** 2 + ($py - $ay) ** 2)
                : abs($dy * $px - $dx * $py + $bx * $ay - $by * $ax) / $len;
            ($worst, $worstD) = ($k, $d) if $d > $worstD;
        }
        if (defined $worst) { $keep{$worst} = 1; push @stack, [$i, $worst], [$worst, $j] }
    }
    return map { $pts->[$_] } sort { $a <=> $b } keys %keep;
}
