#!/usr/bin/env python3
"""Generate Data/Tiles.lua from a game version's own data.

Each map's WDT (MAID chunk) lists the exact minimap FileDataID for every tile
*that version* uses, so we never guess IDs or rely on the retail listfile
(which includes tiles other versions never reference).

  local: reads the install's own Map.db2 and includes every open-world map,
         dungeon and raid that has minimap tiles.
  wago:  pulls files from wago.tools. By default only the four classic
         continents (as before); --all-maps reads Map.db2 like local mode.

  python3 tools/gen_tiles.py local "/Applications/World of Warcraft" wow_classic_beta \\
      -o Data/Tiles.lua

"""
from __future__ import annotations

import argparse
import sys

from mmtools.formats import blp_edge_colors, wdt_maid
from mmtools.log import log
from mmtools.luaout import lua_str
from mmtools.maps import MAP_DB2, MapInfo, read_maps
from mmtools.sources import Source, add_source_args, source_from_args

CLASSIC_CONTINENTS = [
    MapInfo(0, 775971, "Eastern Kingdoms"),
    MapInfo(1, 782779, "Kalimdor"),
    MapInfo(530, 828395, "Outland"),
    MapInfo(571, 822688, "Northrend"),
]
BG_SAMPLES = 24  # edge tiles sampled per map for the backdrop colour


def median(values):
    s = sorted(values)
    return s[len(s) // 2]


def map_list(src: Source, all_maps: bool) -> list[MapInfo]:
    if not all_maps:
        return CLASSIC_CONTINENTS
    data = src.read(MAP_DB2)
    if data is None:
        raise SystemExit("Map.db2 not available")
    return read_maps(data)


def edge_samples(tiles: dict[int, int]) -> list[tuple[int, dict]]:
    """Up to BG_SAMPLES tiles along the map's outer edge, with the sides
    that face empty space: (minimap FDID, sides)."""
    edge = []
    for key in sorted(tiles):
        sides = {"left": key - 64 not in tiles, "right": key + 64 not in tiles,
                 "top": key - 1 not in tiles, "bottom": key + 1 not in tiles}
        if any(sides.values()):
            edge.append((tiles[key], sides))
    step = len(edge) / BG_SAMPLES if len(edge) > BG_SAMPLES else 1
    out, i = [], 0.0
    while i < len(edge):
        out.append(edge[int(i)])
        i += step
    return out


def write_tiles(out, src: Source, maps: list[MapInfo], tiles_of: dict, samples: dict) -> None:
    w = out.write
    w(f"-- GENERATED by tools/gen_tiles.py from the {src.product} {src.version} WDT files. Do not edit.\n")
    w("-- tiles[col * 64 + row] = minimap FileDataID for map<col>_<row>\n")
    w("-- bg = median colour of the water along the map's outer edge (for the backdrop)\n")
    w("-- kind = \"dungeon\" | \"raid\" for instances (nil: open world); continent = instanceID of the entrance's continent\n")
    w(f"MagicMap_Tiles = {{ product = \"{src.product}\", version = \"{src.version}\", maps = {{\n")
    for m in sorted(maps, key=lambda m: m.inst):
        tiles = tiles_of.get(m.inst)
        if not tiles:
            continue
        colors = []
        for fdid, sides in samples.get(m.inst, []):
            blp = src.read(fdid)
            if blp is not None:
                colors.extend(blp_edge_colors(blp, sides))
        bg = ("{ %.3f, %.3f, %.3f }" % tuple(median(c[k] for c in colors) for k in range(3))) if colors else "nil"
        instance = ""
        if m.kind:
            instance = f", kind = \"{m.kind}\"" + (f", continent = {m.continent}" if m.continent is not None else "")
        w(f"  [{m.inst}] = {{ name = {lua_str(m.name)}, bg = {bg}{instance}, tiles = {{\n")
        keys = sorted(tiles)
        for i in range(0, len(keys), 8):
            w("    " + " ".join(f"[{k}]={tiles[k]}," for k in keys[i:i + 8]) + "\n")
        w("  } },\n")
        log(f"{src.product} {src.version}: [{m.inst}] {m.name} {len(tiles)} tiles, bg {bg}")
    w("} }\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    add_source_args(parser)
    parser.add_argument("-o", "--output", help="tiles file (default: stdout)")
    parser.add_argument("--all-maps", action="store_true", help="wago: every map in Map.db2, not just the continents")
    ns = parser.parse_args()
    src = source_from_args(parser, ns)
    maps = map_list(src, ns.mode == "local" or ns.all_maps)

    src.prefetch(m.wdt for m in maps)
    tiles_of, samples = {}, {}
    for m in maps:
        wdt = src.read(m.wdt)
        if wdt is None or wdt[:4] != b"REVM":
            continue
        tiles = {k: t.minimap for k, t in wdt_maid(wdt).items() if t.minimap}
        if tiles:
            tiles_of[m.inst] = tiles
            samples[m.inst] = edge_samples(tiles)
    src.prefetch(fdid for s in samples.values() for fdid, _ in s)

    if ns.output:
        with open(ns.output, "w", encoding="utf-8", newline="\n") as f:
            write_tiles(f, src, maps, tiles_of, samples)
    else:
        write_tiles(sys.stdout, src, maps, tiles_of, samples)


if __name__ == "__main__":
    main()
