#!/usr/bin/env python3
"""Generate Data/Tiles_<product>.lua (and optionally Data/Heights_<product>.lua)
from a game version's own data.

Each map's WDT (MAID chunk) lists the exact minimap FileDataID for every tile
*that version* uses, so we never guess IDs or rely on the retail listfile
(which includes tiles other versions never reference).

  local: reads the install's own Map.db2 and includes every open-world map,
         dungeon and raid that has minimap tiles.
  wago:  pulls files from wago.tools. By default only the four classic
         continents (as before); --all-maps reads Map.db2 like local mode.

  python3 tools/gen_tiles.py local "/Applications/World of Warcraft" wow_classic_beta \\
      --heights Data/Heights_wow_classic_beta.lua -o Data/Tiles_wow_classic_beta.lua
  python3 tools/gen_tiles.py wago wow_classic_era -o Data/Tiles_wow_classic_era.lua

Heights are one byte per 33-yard chunk (16x16 per tile), open world only.
"""
from __future__ import annotations

import argparse
import sys

from mmtools.formats import adt_chunks, blp_edge_colors, wdt_maid
from mmtools.luaout import lua_bytes, lua_str
from mmtools.maps import MAP_DB2, MapInfo, read_maps
from mmtools.sources import Source, add_source_args, source_from_args

CLASSIC_CONTINENTS = [
    MapInfo(0, 775971, "Eastern Kingdoms"),
    MapInfo(1, 782779, "Kalimdor"),
    MapInfo(530, 828395, "Outland"),
    MapInfo(571, 822688, "Northrend"),
]
BG_SAMPLES = 24  # edge tiles sampled per map for the backdrop colour


def log(msg: str) -> None:
    print(msg, file=sys.stderr)


def median(values):
    s = sorted(values)
    return s[len(s) // 2]


def map_list(src: Source, all_maps: bool) -> list[MapInfo]:
    if not all_maps:
        return CLASSIC_CONTINENTS
    data = src.read(MAP_DB2)
    if data is None:
        raise SystemExit("Map.db2 not available")
    return read_maps(data)


def edge_samples(tiles: dict[int, int]) -> list[tuple[int, dict]]:
    """Up to BG_SAMPLES tiles along the map's outer edge, with the sides
    that face empty space: (minimap FDID, sides)."""
    edge = []
    for key in sorted(tiles):
        sides = {"left": key - 64 not in tiles, "right": key + 64 not in tiles,
                 "top": key - 1 not in tiles, "bottom": key + 1 not in tiles}
        if any(sides.values()):
            edge.append((tiles[key], sides))
    step = len(edge) / BG_SAMPLES if len(edge) > BG_SAMPLES else 1
    out, i = [], 0.0
    while i < len(edge):
        out.append(edge[int(i)])
        i += step
    return out


def write_tiles(out, src: Source, maps: list[MapInfo], tiles_of: dict, samples: dict) -> None:
    w = out.write
    w(f"-- GENERATED by tools/gen_tiles.py from the {src.product} {src.version} WDT files. Do not edit.\n")
    w("-- tiles[col * 64 + row] = minimap FileDataID for map<col>_<row>\n")
    w("-- bg = median colour of the water along the map's outer edge (for the backdrop)\n")
    w("-- kind = \"dungeon\" | \"raid\" for instances (nil: open world); continent = instanceID of the entrance's continent\n")
    w(f"if not MagicMap_WantTileSet(\"{src.product}\", \"{src.version}\") then return end\n")
    w(f"MagicMap_ActiveProduct = \"{src.product}\"\n")
    w("MagicMap_TileSets = MagicMap_TileSets or {}\n")
    w(f"MagicMap_TileSets[\"{src.product}\"] = {{ version = \"{src.version}\", maps = {{\n")
    for m in sorted(maps, key=lambda m: m.inst):
        tiles = tiles_of.get(m.inst)
        if not tiles:
            continue
        colors = []
        for fdid, sides in samples.get(m.inst, []):
            blp = src.read(fdid)
            if blp is not None:
                colors.extend(blp_edge_colors(blp, sides))
        bg = ("{ %.3f, %.3f, %.3f }" % tuple(median(c[k] for c in colors) for k in range(3))) if colors else "nil"
        instance = ""
        if m.kind:
            instance = f", kind = \"{m.kind}\"" + (f", continent = {m.continent}" if m.continent is not None else "")
        w(f"  [{m.inst}] = {{ name = {lua_str(m.name)}, bg = {bg}{instance}, tiles = {{\n")
        keys = sorted(tiles)
        for i in range(0, len(keys), 8):
            w("    " + " ".join(f"[{k}]={tiles[k]}," for k in keys[i:i + 8]) + "\n")
        w("  } },\n")
        log(f"{src.product} {src.version}: [{m.inst}] {m.name} {len(tiles)} tiles, bg {bg}")
    w("} }\n")


# --- heights ------------------------------------------------------------------
# One byte per 33-yard chunk (16x16 per tile), quantized per map as
# height = min + level * scale. A tile is a 256-byte string, row by row
# (byte iy*16 + ix + 1), or a single byte when the whole tile is one level
# (open sea). Bytes are raw except those a Lua string literal can't hold; each
# map rotates its levels by `shift` so as few as possible need escaping.

def adt_heights(adt: bytes) -> dict[int, float]:
    """Mean height of each chunk: {iy * 16 + ix: yards}."""
    h = {}
    for c in adt_chunks(adt):
        if c.heights is not None and c.ix < 16 and c.iy < 16:
            h[c.iy * 16 + c.ix] = c.mean_height
    return h


def best_shift(hist: dict[int, int]) -> int:
    best = None
    for k in range(256):
        cost = sum(n for q, n in hist.items() if ((q + k) % 256) < 32 or (q + k) % 256 in (34, 92, 127))
        if best is None or cost < best[1]:
            best = (k, cost)
    return best[0]


def write_heights(out, src: Source, maps: list[MapInfo], tiles_of: dict, adts_of: dict) -> None:
    w = out.write
    w(f"-- GENERATED by tools/gen_tiles.py from the {src.product} {src.version} terrain (ADT chunk heights). Do not edit.\n".encode())
    w(b"-- tiles[col * 64 + row] = 256 bytes (or 1 for a flat tile), chunk (ix, iy) at byte iy * 16 + ix + 1;\n")
    w(b"-- height in yards = min + ((byte - shift) % 256) * scale\n")
    w(f"if not MagicMap_WantHeights(\"{src.product}\", \"{src.version}\") then return end\n".encode())
    w(b"MagicMap_Heights = {\n")
    for m in sorted(maps, key=lambda m: m.inst):
        if m.kind:
            continue  # open world only: keeps the file small
        adts, tiles = adts_of.get(m.inst), tiles_of.get(m.inst)
        if not adts or not tiles:
            continue
        keys = sorted(k for k in adts if k in tiles)
        if not keys:
            continue
        src.prefetch(adts[k] for k in keys)
        h = {}
        for key in keys:
            adt = src.read(adts[key])
            t = adt_heights(adt) if adt is not None else {}
            if t:
                h[key] = t
        if not h:
            continue
        lo = min(min(t.values()) for t in h.values())
        hi = max(max(t.values()) for t in h.values())
        scale = (hi - lo) / 255 or 1
        levels, hist = {}, {}
        for key, t in h.items():
            mean = sum(t[i] for i in sorted(t)) / len(t)
            q = [int((t.get(i, mean) - lo) / scale + 0.5) for i in range(256)]
            if all(v == q[0] for v in q):
                q = [q[0]]
            levels[key] = q
            for v in q:
                hist[v] = hist.get(v, 0) + 1
        shift = best_shift(hist)
        name = m.name.replace("\n", " ")
        w(("  [%d] = { min = %.2f, scale = %.4f, shift = %d, tiles = { -- %s\n" % (m.inst, lo, scale, shift, name)).encode())
        size = 0
        for key in sorted(h):
            s = bytes((v + shift) % 256 for v in levels[key])
            size += len(s)
            w(f"    [{key}]=".encode() + lua_bytes(s) + b",\n")
        w(b"  } },\n")
        log("%s %s: [%d] %s heights: %d tiles, %.1f..%.1f yd, %d KB"
            % (src.product, src.version, m.inst, m.name, len(h), lo, hi, size // 1024))
    w(b"}\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    add_source_args(parser)
    parser.add_argument("-o", "--output", help="tiles file (default: stdout)")
    parser.add_argument("--heights", metavar="FILE", help="also write terrain heights to FILE")
    parser.add_argument("--all-maps", action="store_true", help="wago: every map in Map.db2, not just the continents")
    ns = parser.parse_args()
    src = source_from_args(parser, ns)
    maps = map_list(src, ns.mode == "local" or ns.all_maps)

    src.prefetch(m.wdt for m in maps)
    tiles_of, adts_of, samples = {}, {}, {}
    for m in maps:
        wdt = src.read(m.wdt)
        if wdt is None or wdt[:4] != b"REVM":
            continue
        maid = wdt_maid(wdt)
        adts_of[m.inst] = {k: t.root_adt for k, t in maid.items() if t.root_adt}
        tiles = {k: t.minimap for k, t in maid.items() if t.minimap}
        if tiles:
            tiles_of[m.inst] = tiles
            samples[m.inst] = edge_samples(tiles)
    src.prefetch(fdid for s in samples.values() for fdid, _ in s)

    if ns.output:
        with open(ns.output, "w", encoding="utf-8", newline="\n") as f:
            write_tiles(f, src, maps, tiles_of, samples)
    else:
        write_tiles(sys.stdout, src, maps, tiles_of, samples)
    if ns.heights:
        with open(ns.heights, "wb") as f:
            write_heights(f, src, maps, tiles_of, adts_of)


if __name__ == "__main__":
    main()
